servers:
- name: mongodb-s1
  ip: localhost
  data_dir: "/data1"
  disk_partition: "/dev/sdc1"
  file_system: xfs
  logpath: "/tmp/mongod1.log"
  swapfile: "/data1/swapfile"
  swapbs: 1024
  swapcount: 20485760
  mongod: "/home/modb/mongodb/bin/mongod"
  mongo: "/home/modb/mongodb/bin/mongo"
  cpu_affinity: 1
  process: mongod
  port: '27018'
  host: mongodb-s1:27018
- name: mongodb-s2
  ip: localhost
  data_dir: "/data2"
  disk_partition: "/dev/sdc1"
  file_system: xfs
  logpath: "/tmp/mongod2.log"
  swapfile: "/data2/swapfile"
  swapbs: 1024
  swapcount: 20485760
  mongod: "/home/modb/mongodb/bin/mongod"
  mongo: "/home/modb/mongodb/bin/mongo"
  cpu_affinity: 2
  process: mongod
  port: '27019'
  host: mongodb-s2:27019
- name: mongodb-s3
  ip: localhost
  data_dir: "/data3"
  disk_partition: "/dev/sdc1"
  file_system: xfs
  logpath: "/tmp/mongod3.log"
  swapfile: "/data3/swapfile"
  swapbs: 1024
  swapcount: 20485760
  mongod: "/home/modb/mongodb/bin/mongod"
  mongo: "/home/modb/mongodb/bin/mongo"
  cpu_affinity: 3
  process: mongod
  port: '27020'
  host: mongodb-s3:27020
client:
  name: mongodb-client
  mongod: "/home/modb/mongodb/bin/mongod"
  mongo: "/home/modb/mongodb/bin/mongo"
  ycsb: "/home/modb/ycsb-0.17.0/bin/ycsb"