#!/usr/bin/env xonsh

SUBSCRIPTION = "Microsoft Azure Sponsorship 2"
RESOURCE_GROUP = "DepFast_jp"
MONGOD = "/home/modb/mongodb/bin/mongod"
MONGO = "/home/modb/mongodb/bin/mongo"
YCSB = "/home/modb/ycsb-0.17.0/bin/ycsb"
VM_TYPE="Standard_D4s_v3"
ZONE="1"
IMAGE="debian"
OS_DISK_SIZE="30"
DATA_DISK_SIZE="4"
STORAGE_SKU="Standard_LRS"
SLOW_SCRIPTS_PATH = "./../slowness/"
HOSTID = "modb"
