servers:
- hostname: rethink-1
  ip: localhost
  data_dir: "/data1"
  ramdisk_size: 1500M
  cpu_affinity: "0"
  free_cpus: "7,8"
  quorum_process: rethinkdb
  port_offset: 0
- hostname: rethink-2
  ip: localhost
  data_dir: "/data2"
  ramdisk_size: 1500M
  cpu_affinity: "1"
  free_cpus: "7,8"
  quorum_process: rethinkdb
  port_offset: 1
- hostname: rethink-3
  ip: localhost
  data_dir: "/data3"
  ramdisk_size: 1500M
  cpu_affinity: "2"
  free_cpus: "7,8"
  quorum_process: rethinkdb
  port_offset: 2
client:
  hostname: rethinkdb-client
  ycsb: "./YCSB/bin/ycsb"
  cpu_affinity: "3,4"
