servers:
- name: tikv1
  ip: localhost
  disk_partition: "/dev/sdc"
  file_system: ext4
  swapfile: "/data1/swapfile"
  swapbs: 1024
  swapcount: 25165824
  ramdisk_size: 1500M
  cpu_affinity: 1
  process: tikv-server
  data_dir: "/data1"
  port_offset: 0
  server_type: tikv_servers
- name: tikv2
  ip: localhost
  disk_partition: "/dev/sdc"
  file_system: ext4
  swapfile: "/data2/swapfile"
  swapbs: 1024
  swapcount: 25165824
  ramdisk_size: 1500M
  cpu_affinity: 2
  process: tikv-server
  data_dir: "/data2"
  port_offset: 1
  server_type: tikv_servers
- name: tikv3
  ip: localhost
  disk_partition: "/dev/sdc"
  file_system: ext4
  swapfile: "/data3/swapfile"
  swapbs: 1024
  swapcount: 25165824
  ramdisk_size: 1500M
  cpu_affinity: 3
  process: tikv-server
  data_dir: "/data3/"
  port_offset: 2
  server_type: tikv_servers
- name: pd
  ip: localhost
  disk_partition: "/dev/sdc"
  file_system: ext4
  swapfile: "/data0/swapfile"
  swapbs: 1024
  swapcount: 25165824
  ramdisk_size: 1500M
  cpu_affinity: 0
  data_dir: "/data0"
  tiup: "~/.tiup/bin/tiup"
  server_type: pd_server
client:
  name: client
  ip: localhost
  ycsb: "/home/tidb/go-ycsb/bin/go-ycsb"
